"""Bronze-level web scraping source configurations.

Bronze sources require Firecrawl for JS rendering and BeautifulSoup for parsing.
These are the most complex sources requiring custom selectors per site.

Includes:
- Regional government agendas (CLM, Canarias, Navarra, Asturias, La Rioja)
- City agendas (Badajoz, Teruel)
- Viralagenda aggregator (Andalucía, CyL, Galicia, etc.)
"""

from dataclasses import field as dataclass_field

from src.config.sources import (
    BronzeSourceConfig,
    SourceRegistry,
    SourceTier,
)

# ============================================================
# BRONZE SOURCE CONFIGURATIONS
# ============================================================

BRONZE_SOURCES: list[BronzeSourceConfig] = [
    # ============================================================
    # CASTILLA-LA MANCHA
    # ============================================================
    BronzeSourceConfig(
        slug="clm_agenda",
        name="Agenda Cultural de Castilla-La Mancha",
        listing_url="https://agendacultural.castillalamancha.es",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Toledo",  # Default, detected from locality
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        base_url="https://agendacultural.castillalamancha.es",
        event_card_selector=".view-actividades .views-row article.node--type-actividad",
        title_selector=".field--name-title p",
        link_selector="a.article__link",
        image_selector=".field--name-field-image img",
        date_selector=".field--name-field-fecha-actividad",
        location_selector=".field--name-field-localidad-actividad",
        venue_selector=".field--name-field-lugar-actividad",
        requires_detail_fetch=True,
        max_pages=5,
        detail_url_pattern="https://agendacultural.castillalamancha.es{id}",
        detail_id_extractor="url_suffix",
    ),
    # ============================================================
    # CANARIAS (2 sources)
    # ============================================================
    BronzeSourceConfig(
        slug="canarias_lagenda",
        name="Lagenda - Agenda de eventos en Tenerife",
        listing_url="https://lagenda.org/programacion",
        ccaa="Canarias",
        ccaa_code="CN",
        province="Santa Cruz de Tenerife",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        event_card_selector=".small-post",
        title_selector="h4.title a",
        image_selector=".thumb img",
        date_selector=".post-date .date-display-single",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="canarias_grancanaria",
        name="Cultura Gran Canaria - Cabildo",
        listing_url="https://cultura.grancanaria.com/agenda/",
        ccaa="Canarias",
        ccaa_code="CN",
        province="Las Palmas",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        event_card_selector=".calendar-booking-item",
        title_selector="h3.title",
        link_selector="a[href*=detalle-agenda]",
        image_selector="",  # No images in listing
        date_selector=".time-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ============================================================
    # ARAGÓN (Teruel)
    # ============================================================
    BronzeSourceConfig(
        slug="teruel_ayuntamiento",
        name="Agenda Cultural Ayuntamiento de Teruel",
        listing_url="https://www.teruel.es/eventos/feed/",
        ccaa="Aragón",
        ccaa_code="AR",
        province="Teruel",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        firecrawl_url="https://firecrawl.si-erp.cloud/v1/scrape",
        base_url="https://www.teruel.es",
        event_card_selector="item",
        title_selector="title",
        link_selector="link",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="{id}",
        detail_id_extractor="url_suffix",
    ),
    # ============================================================
    # NAVARRA
    # ============================================================
    BronzeSourceConfig(
        slug="navarra_cultura",
        name="Cultura Navarra - Gobierno de Navarra",
        listing_url="https://www.culturanavarra.es/es/agenda",
        ccaa="Navarra",
        ccaa_code="NA",
        province="Navarra",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        base_url="https://www.culturanavarra.es/",
        event_card_selector=".agenda_evento",
        title_selector="h4 a",
        link_selector="h4 a",
        image_selector="img.btn-block",
        date_selector=".fecha",
        category_selector="h3",
        location_selector=".localidad span:last-child",
        venue_selector=".localidad span:first-child",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.culturanavarra.es/{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".entradilla, .descripcion, article .content",
    ),
    # ============================================================
    # ASTURIAS
    # ============================================================
    BronzeSourceConfig(
        slug="asturias_turismo",
        name="Turismo Asturias - Agenda de Eventos",
        listing_url="https://www.turismoasturias.es/es/agenda-de-asturias",
        ccaa="Principado de Asturias",
        ccaa_code="AS",
        province="Asturias",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        base_url="https://www.turismoasturias.es",
        event_card_selector=".card",
        title_selector=".card-title",
        link_selector="a",
        image_selector="img",
        requires_detail_fetch=True,
        max_pages=3,
        pagination_type="liferay",
        liferay_portlet_id="as_asac_calendar_suite_CalendarSuitePortlet_INSTANCE_JXvXAPSD7JC0",
        items_per_page=9,
        detail_url_pattern="{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector='[itemprop="description"], .text[itemprop="description"], div.text',
    ),
    # ============================================================
    # LA RIOJA - Usa adapter Gold (ver gold_sources.py)
    # ============================================================
    # ============================================================
    # EXTREMADURA (Badajoz)
    # ============================================================
    BronzeSourceConfig(
        slug="badajoz_agenda",
        name="Agenda Cultural Ayuntamiento de Badajoz",
        listing_url="https://www.aytobadajoz.es/es/ayto/agenda/",
        ccaa="Extremadura",
        ccaa_code="EX",
        province="Badajoz",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        base_url="https://www.aytobadajoz.es",
        event_card_selector=".agenda-listado.evento",
        title_selector=".titulo a",
        link_selector=".titulo a",
        image_selector=".imagen-evento img",
        date_selector=".fechas-agenda-menu-actualidad",
        category_selector=".categoria-agenda",
        time_selector=".info-evento-agenda .fa-clock",
        venue_selector=".info-evento-agenda .fa-map-marker-alt",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".descripcion-evento, .texto-evento, .contenido-evento, .cuerpo-principal",
    ),
    # ============================================================
    # VIRALAGENDA SOURCES
    # These use the same structure, different URLs per province
    # ============================================================
    # ---- EXTREMADURA (Cáceres) ----
    BronzeSourceConfig(
        slug="viralagenda_caceres",
        name="Viral Agenda - Cáceres",
        listing_url="https://www.viralagenda.com/es/extremadura/caceres/caceres",
        ccaa="Extremadura",
        ccaa_code="EX",
        province="Cáceres",
        city="Cáceres",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- ANDALUCÍA (8 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_almeria",
        name="Viral Agenda - Almería",
        listing_url="https://www.viralagenda.com/es/andalucia/almeria",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Almería",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_cadiz",
        name="Viral Agenda - Cádiz",
        listing_url="https://www.viralagenda.com/es/andalucia/cadiz",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Cádiz",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_cordoba",
        name="Viral Agenda - Córdoba",
        listing_url="https://www.viralagenda.com/es/andalucia/cordoba",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Córdoba",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_granada",
        name="Viral Agenda - Granada",
        listing_url="https://www.viralagenda.com/es/andalucia/granada",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Granada",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_huelva",
        name="Viral Agenda - Huelva",
        listing_url="https://www.viralagenda.com/es/andalucia/huelva",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Huelva",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_jaen",
        name="Viral Agenda - Jaén",
        listing_url="https://www.viralagenda.com/es/andalucia/jaen",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Jaén",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_malaga",
        name="Viral Agenda - Málaga",
        listing_url="https://www.viralagenda.com/es/andalucia/malaga",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Málaga",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_sevilla",
        name="Viral Agenda - Sevilla",
        listing_url="https://www.viralagenda.com/es/andalucia/sevilla",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Sevilla",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- CASTILLA Y LEÓN (9 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_avila",
        name="Viral Agenda - Ávila",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/avila",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Ávila",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_burgos",
        name="Viral Agenda - Burgos",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/burgos",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Burgos",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_leon",
        name="Viral Agenda - León",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/leon",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="León",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_palencia",
        name="Viral Agenda - Palencia",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/palencia",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Palencia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_salamanca",
        name="Viral Agenda - Salamanca",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/salamanca",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Salamanca",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_segovia",
        name="Viral Agenda - Segovia",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/segovia",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Segovia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_soria",
        name="Viral Agenda - Soria",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/soria",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Soria",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_valladolid",
        name="Viral Agenda - Valladolid",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/valladolid",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Valladolid",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_zamora",
        name="Viral Agenda - Zamora",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/zamora",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Zamora",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- GALICIA (4 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_a_coruna",
        name="Viral Agenda - A Coruña",
        listing_url="https://www.viralagenda.com/es/galicia/a-coruna",
        ccaa="Galicia",
        ccaa_code="GA",
        province="A Coruña",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_lugo",
        name="Viral Agenda - Lugo",
        listing_url="https://www.viralagenda.com/es/galicia/lugo",
        ccaa="Galicia",
        ccaa_code="GA",
        province="Lugo",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_ourense",
        name="Viral Agenda - Ourense",
        listing_url="https://www.viralagenda.com/es/galicia/ourense",
        ccaa="Galicia",
        ccaa_code="GA",
        province="Ourense",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_pontevedra",
        name="Viral Agenda - Pontevedra",
        listing_url="https://www.viralagenda.com/es/galicia/pontevedra",
        ccaa="Galicia",
        ccaa_code="GA",
        province="Pontevedra",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- ASTURIAS (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_asturias",
        name="Viral Agenda - Asturias",
        listing_url="https://www.viralagenda.com/es/asturias",
        ccaa="Principado de Asturias",
        ccaa_code="AS",
        province="Asturias",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- CANARIAS (Viralagenda - 2 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_las_palmas",
        name="Viral Agenda - Las Palmas",
        listing_url="https://www.viralagenda.com/es/canarias/las-palmas",
        ccaa="Canarias",
        ccaa_code="CN",
        province="Las Palmas",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_santa_cruz_tenerife",
        name="Viral Agenda - Santa Cruz de Tenerife",
        listing_url="https://www.viralagenda.com/es/canarias/santa-cruz-de-tenerife",
        ccaa="Canarias",
        ccaa_code="CN",
        province="Santa Cruz de Tenerife",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- CANTABRIA (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_cantabria",
        name="Viral Agenda - Cantabria",
        listing_url="https://www.viralagenda.com/es/cantabria",
        ccaa="Cantabria",
        ccaa_code="CB",
        province="Cantabria",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- LA RIOJA ----
    # No hay Viralagenda para La Rioja (404)
    # Solo tiene: larioja_agenda (bronze), eventbrite_la_rioja (eventbrite)
    # ---- MURCIA (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_murcia",
        name="Viral Agenda - Murcia",
        listing_url="https://www.viralagenda.com/es/murcia",
        ccaa="Región de Murcia",
        ccaa_code="MC",
        province="Murcia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- NAVARRA (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_navarra",
        name="Viral Agenda - Navarra",
        listing_url="https://www.viralagenda.com/es/navarra",
        ccaa="Navarra",
        ccaa_code="NC",
        province="Navarra",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- PAÍS VASCO (Viralagenda - 3 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_araba",
        name="Viral Agenda - Araba/Álava",
        listing_url="https://www.viralagenda.com/es/pais-vasco/araba-alava",
        ccaa="País Vasco",
        ccaa_code="PV",
        province="Araba/Álava",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_bizkaia",
        name="Viral Agenda - Bizkaia",
        listing_url="https://www.viralagenda.com/es/pais-vasco/bizkaia",
        ccaa="País Vasco",
        ccaa_code="PV",
        province="Bizkaia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_gipuzkoa",
        name="Viral Agenda - Gipuzkoa",
        listing_url="https://www.viralagenda.com/es/pais-vasco/gipuzkoa",
        ccaa="País Vasco",
        ccaa_code="PV",
        province="Gipuzkoa",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- ARAGÓN (Viralagenda - 3 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_huesca",
        name="Viral Agenda - Huesca",
        listing_url="https://www.viralagenda.com/es/aragon/huesca",
        ccaa="Aragón",
        ccaa_code="AR",
        province="Huesca",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_teruel",
        name="Viral Agenda - Teruel",
        listing_url="https://www.viralagenda.com/es/aragon/teruel",
        ccaa="Aragón",
        ccaa_code="AR",
        province="Teruel",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_zaragoza",
        name="Viral Agenda - Zaragoza",
        listing_url="https://www.viralagenda.com/es/aragon/zaragoza",
        ccaa="Aragón",
        ccaa_code="AR",
        province="Zaragoza",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- COMUNITAT VALENCIANA (Viralagenda - 3 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_alicante",
        name="Viral Agenda - Alicante",
        listing_url="https://www.viralagenda.com/es/comunitat-valenciana/alicante",
        ccaa="Comunitat Valenciana",
        ccaa_code="VC",
        province="Alicante",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_castellon",
        name="Viral Agenda - Castellón",
        listing_url="https://www.viralagenda.com/es/comunitat-valenciana/castellon",
        ccaa="Comunitat Valenciana",
        ccaa_code="VC",
        province="Castellón",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_valencia",
        name="Viral Agenda - Valencia",
        listing_url="https://www.viralagenda.com/es/comunitat-valenciana/valencia",
        ccaa="Comunitat Valenciana",
        ccaa_code="VC",
        province="Valencia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- CATALUÑA (Viralagenda - 4 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_barcelona",
        name="Viral Agenda - Barcelona",
        listing_url="https://www.viralagenda.com/es/cataluna/barcelona",
        ccaa="Cataluña",
        ccaa_code="CT",
        province="Barcelona",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_girona",
        name="Viral Agenda - Girona",
        listing_url="https://www.viralagenda.com/es/cataluna/girona",
        ccaa="Cataluña",
        ccaa_code="CT",
        province="Girona",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_lleida",
        name="Viral Agenda - Lleida",
        listing_url="https://www.viralagenda.com/es/cataluna/lleida",
        ccaa="Cataluña",
        ccaa_code="CT",
        province="Lleida",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_tarragona",
        name="Viral Agenda - Tarragona",
        listing_url="https://www.viralagenda.com/es/cataluna/tarragona",
        ccaa="Cataluña",
        ccaa_code="CT",
        province="Tarragona",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- ILLES BALEARS ----
    # No hay Viralagenda para Baleares (404)
    # illesbalears.travel tiene muy pocos eventos
    # Eventbrite bloquea páginas de detalle
    # Región sin scraper por ahora
    # ---- COMUNIDAD DE MADRID (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_madrid",
        name="Viral Agenda - Madrid",
        listing_url="https://www.viralagenda.com/es/madrid",
        ccaa="Comunidad de Madrid",
        ccaa_code="MD",
        province="Madrid",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- CASTILLA-LA MANCHA (Viralagenda - 5 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_albacete",
        name="Viral Agenda - Albacete",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/albacete",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Albacete",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_ciudad_real",
        name="Viral Agenda - Ciudad Real",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/ciudad-real",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Ciudad Real",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_cuenca",
        name="Viral Agenda - Cuenca",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/cuenca",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Cuenca",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_guadalajara",
        name="Viral Agenda - Guadalajara",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/guadalajara",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Guadalajara",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    BronzeSourceConfig(
        slug="viralagenda_toledo",
        name="Viral Agenda - Toledo",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/toledo",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Toledo",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ---- EXTREMADURA (Viralagenda - 2 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_badajoz",
        name="Viral Agenda - Badajoz",
        listing_url="https://www.viralagenda.com/es/extremadura/badajoz",
        ccaa="Extremadura",
        ccaa_code="EX",
        province="Badajoz",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        category_selector=".viral-event-cats a",
        location_selector=".viral-event-places",
        base_url="https://www.viralagenda.com",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.viralagenda.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".viral-event-description, .description, article",
    ),
    # ============================================================
    # SOCIAL CATEGORY SOURCES (custom adapters)
    # ============================================================
    # ---- VACACIONES SENIORS (National - Senior travel circuits) ----
    BronzeSourceConfig(
        slug="vacacionesseniors",
        name="Vacaciones Seniors - Circuitos para mayores",
        listing_url="https://vacacionesseniors.com/circuitos-culturales-salidas-desde-madrid/",
        ccaa="Comunidad de Madrid",  # Base location (departure point)
        ccaa_code="MD",
        province="Madrid",
        city="Madrid",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,  # Uses Firecrawl for JS-rendered price tables
        event_card_selector="article.dp-dfg-item",
        title_selector=".dp-dfg-header h1",
        link_selector="a[href*='vacacionesseniors.com']",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- DONAR SANGRE (Madrid - Blood donation mobile points) ----
    BronzeSourceConfig(
        slug="donarsangre",
        name="Donar Sangre - Puntos Móviles de Donación",
        listing_url="https://www.donarsangre.org/proximos-puntos-moviles/",
        ccaa="Comunidad de Madrid",
        ccaa_code="MD",
        province="Madrid",
        city="Madrid",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,  # Simple HTML, no JS needed
        event_card_selector="li",
        title_selector="a",
        link_selector="a",
        requires_detail_fetch=False,  # All info in listing page
        max_pages=1,
    ),
    # ---- SOLEDAD NO DESEADA (Madrid - Social activities against loneliness) ----
    # DESACTIVADA: La web no tiene fechas con año, genera fechas falsas futuras
    BronzeSourceConfig(
        slug="soledadnodeseada",
        name="Soledad No Deseada - Actividades contra la soledad",
        listing_url="https://soledadnodeseada.es/actividades/",
        ccaa="Comunidad de Madrid",
        ccaa_code="MD",
        province="Madrid",
        city="Madrid",
        tier=SourceTier.BRONZE,
        is_active=False,  # Desactivada - eventos sin año explícito
        uses_firecrawl=True,  # Uses Firecrawl with actions for dynamic "load more"
        event_card_selector="a[href*='/actividades/']",
        title_selector="title",
        link_selector="a[href*='/actividades/']",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ============================================================
    # SANITARIA CATEGORY SOURCES (custom adapters)
    # ============================================================
    # ---- CON SALUD MENTAL (Nacional - Mental health events) ----
    BronzeSourceConfig(
        slug="consaludmental",
        name="Confederación Salud Mental España",
        listing_url="https://consaludmental.org/listado-eventos/",
        ccaa="Nacional",
        ccaa_code="ES",
        province="",  # National scope
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,  # Uses WordPress REST API
        event_card_selector="",  # Custom adapter handles parsing
        title_selector="",
        link_selector="",
        requires_detail_fetch=False,  # API returns full data
        max_pages=1,
    ),
    # ============================================================
    # TECNOLOGÍA CATEGORY SOURCES (digital inclusion adapters)
    # ============================================================
    # ---- OVIEDO DIGITAL (Asturias - Digital competence courses) ----
    BronzeSourceConfig(
        slug="oviedo_digital",
        name="Oviedo, Ciudadanía Digital",
        listing_url="https://centrosocialvirtualoviedo.es/actividades",
        ccaa="Principado de Asturias",
        ccaa_code="AS",
        province="Asturias",
        city="Oviedo",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="",  # Custom text-based parsing
        title_selector="",
        link_selector="",
        requires_detail_fetch=False,
        max_pages=1,
    ),
    # ---- CEMIT GALICIA (Galicia - Xunta digital training) ----
    BronzeSourceConfig(
        slug="cemit_galicia",
        name="CeMIT Galicia - Formación Presencial",
        listing_url="https://cemit.xunta.gal/es/formacion/formacion-presencial",
        ccaa="Galicia",
        ccaa_code="GA",
        province="",  # Multiple provinces
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="div.activity",
        title_selector=".activity-name a",
        link_selector=".activity-name a",
        requires_detail_fetch=False,
        max_pages=6,
    ),
    # ---- PUNTOS VUELA (Andalucía - Guadalinfo rebranded) ----
    BronzeSourceConfig(
        slug="puntos_vuela",
        name="Puntos Vuela - Andalucía",
        listing_url="https://puntosvuela.es/actividades",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="",  # 8 provinces
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="div.card-event",
        title_selector="h5.card-title",
        link_selector="a.card-body",
        requires_detail_fetch=False,
        max_pages=8,
    ),
    # ============================================================
    # POLÍTICA CATEGORY SOURCES (institutional/civic adapters)
    # ============================================================
    # ---- LA MONCLOA (Nacional - Government daily agenda) ----
    BronzeSourceConfig(
        slug="la_moncloa",
        name="Agenda del Gobierno de España - La Moncloa",
        listing_url="https://www.lamoncloa.gob.es/gobierno/agenda/Paginas/agenda.aspx",
        ccaa="Comunidad de Madrid",
        ccaa_code="MD",
        province="Madrid",
        city="Madrid",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="",  # Custom structural parsing
        title_selector="",
        link_selector="",
        requires_detail_fetch=False,
        max_pages=1,
    ),
    # ---- DEFENSOR DEL PUEBLO (Nacional - Institutional agenda) ----
    BronzeSourceConfig(
        slug="defensor_pueblo",
        name="Defensor del Pueblo - Calendario de Actividades",
        listing_url="https://www.defensordelpueblo.es/agenda-institucional/",
        ccaa="Comunidad de Madrid",
        ccaa_code="MD",
        province="Madrid",
        city="Madrid",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="",  # Custom parsing from month tabs
        title_selector="",
        link_selector="",
        requires_detail_fetch=False,
        max_pages=1,
    ),
    # ---- CNT AGENDA (Nacional - Sindical/civic events) ----
    BronzeSourceConfig(
        slug="cnt_agenda",
        name="CNT - Confederación Nacional del Trabajo",
        listing_url="https://cnt.es/noticias/category/noticias/agenda/",
        ccaa="",  # National scope
        ccaa_code="",
        province="",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="article",
        title_selector=".entry-title a",
        link_selector=".entry-title a",
        requires_detail_fetch=True,
        max_pages=5,
    ),
    # ---- SEGIB (Internacional - Iberoamerican cooperation) ----
    BronzeSourceConfig(
        slug="segib",
        name="SEGIB - Secretaría General Iberoamericana",
        listing_url="https://www.segib.org/sala-de-prensa/",
        ccaa="",  # International scope
        ccaa_code="",
        province="",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.wp-block-post.evento",
        title_selector="h5 a",
        link_selector="h5 a",
        requires_detail_fetch=False,
        max_pages=5,
    ),
    # ---- JGPA (Asturias - Parliamentary calendar) ----
    BronzeSourceConfig(
        slug="jgpa",
        name="Junta General del Principado de Asturias",
        listing_url="https://www.jgpa.es/calendario-de-actividades",
        ccaa="Principado de Asturias",
        ccaa_code="AS",
        province="Asturias",
        city="Oviedo",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="div.calevent-wrapper",
        title_selector="span.title",
        link_selector="a.calevent",
        requires_detail_fetch=False,
        max_pages=1,
    ),
    # ---- HORIZONTE EUROPA (Nacional/UE - Research & innovation) ----
    BronzeSourceConfig(
        slug="horizonte_europa",
        name="Horizonte Europa - Programa europeo de I+D+i",
        listing_url="https://horizonteeuropa.es/eventos",
        ccaa="",  # National/EU scope
        ccaa_code="",
        province="",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="div.fila-pagina-eventos",
        title_selector="div.titulo a",
        link_selector="div.titulo a",
        requires_detail_fetch=False,
        max_pages=5,
    ),
    # ============================================================
    # ECONOMICA CATEGORY SOURCES
    # ============================================================
    # ---- NFERIAS (Nacional - Business/trade fairs) ----
    BronzeSourceConfig(
        slug="nferias",
        name="nFerias - Ferias de Negocios en España",
        listing_url="https://www.nferias.com/negocios/espana/",
        ccaa="",  # National scope
        ccaa_code="",
        province="",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="",  # Custom adapter handles parsing
        title_selector="",
        link_selector="",
        requires_detail_fetch=False,
        max_pages=3,
    ),
    # ---- BARCELONA ACTIVA (Cataluña - Entrepreneurship workshops) ----
    BronzeSourceConfig(
        slug="barcelona_activa",
        name="Barcelona Activa - Emprendimiento",
        listing_url="https://emprenedoria.barcelonactiva.cat/es/activitats/activity-timetable",
        ccaa="Cataluña",
        ccaa_code="CT",
        province="Barcelona",
        city="Barcelona",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,  # Uses Tavily extract
        event_card_selector="",  # Custom adapter handles parsing
        title_selector="",
        link_selector="",
        requires_detail_fetch=False,
        max_pages=1,
    ),
    # ---- TOUR DEL EMPLEO (Nacional - University employment fairs) ----
    BronzeSourceConfig(
        slug="tourdelempleo",
        name="Tour del Empleo - Ferias de Empleo Universitarias",
        listing_url="https://www.tourdelempleo.com/ferias/",
        ccaa="",  # National scope
        ccaa_code="",
        province="",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="",  # Custom adapter handles parsing
        title_selector="",
        link_selector="",
        requires_detail_fetch=False,
        max_pages=1,
    ),
    # ============================================================
    # NUEVAS FUENTES - CCAAs CON BAJA COBERTURA
    # ============================================================
    # ---- CEUTA ----
    BronzeSourceConfig(
        slug="viveceuta",
        name="Vive Ceuta - Agenda Cultural",
        listing_url="https://viveceuta.es/",
        ccaa="Ceuta",
        ccaa_code="CE",
        province="Ceuta",
        city="Ceuta",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        base_url="https://viveceuta.es",
        # WordPress + Elementor + The Events Calendar
        # Cards: div.e-loop-item.tribe_events (6 eventos en home)
        event_card_selector="div.e-loop-item.tribe_events",
        title_selector="h3",
        link_selector='a[href*="/evento/"]',
        image_selector="img",
        date_selector="time, .tribe-event-schedule-details",
        venue_selector=".tribe-venue, .tribe-events-venue-details",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".tribe-events-single-event-description, .tribe-events-content, .entry-content",
    ),
    # ---- MELILLA ----
    # melilla_cultura DESACTIVADA: portal JSP carga contenido via AJAX, no scrappeable sin JS
    BronzeSourceConfig(
        slug="melilla_cultura",
        name="Agenda Cultural de Melilla",
        listing_url="https://www.melilla.es/melillaportal/contenedor.jsp?seccion=s_lact_d10_v1.jsp&codbusqueda=204&language=es&codResi=1&codMenuPN=601&codMenuSN=9&codMenu=810",
        ccaa="Melilla",
        ccaa_code="ML",
        province="Melilla",
        city="Melilla",
        tier=SourceTier.BRONZE,
        is_active=False,  # AJAX-only, no funciona con HTTP directo ni Firecrawl
        uses_firecrawl=False,
        base_url="https://www.melilla.es",
        event_card_selector="div.panel",
        title_selector="a",
        link_selector="a",
        date_selector=".fecha",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- ILLES BALEARS (2 sources) ----
    BronzeSourceConfig(
        slug="visitpalma_agenda",
        name="Visit Palma - Agenda de Eventos",
        listing_url="https://visitpalma.com/es/agenda/",
        ccaa="Illes Balears",
        ccaa_code="IB",
        province="Illes Balears",
        city="Palma",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        base_url="https://visitpalma.com",
        # WordPress plugin Events Calendar Bridge for Elementor (ECTBE)
        # 26 eventos con .ectbe-simple-event
        event_card_selector=".ectbe-simple-event",
        title_selector=".ectbe-evt-title a",
        link_selector=".ectbe-evt-title a",
        image_selector=".ectbe-evt-img img",
        date_selector=".ectbe-date-area",
        category_selector=".ectbe-evt-category",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".ectbe-evt-description, .tribe-events-content, .entry-content",
    ),
    # ---- CANTABRIA (2 sources) ----
    BronzeSourceConfig(
        slug="santander_creativa",
        name="Santander Creativa - Fundación Cultural",
        listing_url="https://www.santandercreativa.com/agenda/hoy",
        ccaa="Cantabria",
        ccaa_code="CB",
        province="Cantabria",
        city="Santander",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        base_url="https://www.santandercreativa.com",
        # App custom — 28 eventos en div.event
        # Titles in .event-title h2, links to /eventos/slug
        event_card_selector="div.event",
        title_selector=".event-title h2",
        link_selector='a[href*="/eventos/"]',
        image_selector="img",
        date_selector=".event-schedule-hours",
        venue_selector=".event-address",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.santandercreativa.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".event-description, .description, .content, article .text",
    ),
    BronzeSourceConfig(
        slug="turismo_santander",
        name="Turismo Santander - Próximos Eventos",
        listing_url="https://turismo.santander.es/actualidad/proximos-eventos",
        ccaa="Cantabria",
        ccaa_code="CB",
        province="Cantabria",
        city="Santander",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        base_url="https://turismo.santander.es",
        # Drupal — 3 eventos en .views-row
        event_card_selector=".views-row",
        title_selector=".views-field-title .field-content a",
        link_selector=".views-field-title .field-content a",
        image_selector=".views-field-field-image img",
        date_selector=".views-field-field-fecha .field-content",
        category_selector=".views-field-field-tags .field-content",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://turismo.santander.es{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".field-name-body, .node-content, article .content",
    ),
    # ---- REGIÓN DE MURCIA ----
    BronzeSourceConfig(
        slug="turismo_murcia",
        name="Turismo Región de Murcia - Agenda",
        listing_url="https://www.turismoregiondemurcia.es/es/agenda/",
        ccaa="Región de Murcia",
        ccaa_code="MC",
        province="Murcia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        base_url="https://www.turismoregiondemurcia.es",
        # CMS custom — 24 eventos en .agenda-card
        # Titles in .agenda-info h6, links via a.agenda-link
        # Images as background-image in .agenda-image style attr
        event_card_selector=".agenda-card",
        title_selector=".agenda-info h6",
        link_selector="a.agenda-link",
        image_selector="img",  # Fallback — real images in background-image style
        date_selector=".agenda-date",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.turismoregiondemurcia.es{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".event-description, .description, .content, article .text",
    ),
    # ---- COMUNITAT VALENCIANA ----
    BronzeSourceConfig(
        slug="visitvalencia_agenda",
        name="Visit Valencia - Agenda de Eventos",
        listing_url="https://www.visitvalencia.com/agenda-valencia",
        ccaa="Comunitat Valenciana",
        ccaa_code="VC",
        province="Valencia",
        city="Valencia",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        base_url="https://www.visitvalencia.com",
        # Drupal custom — 167 eventos en .card--event
        # Titles in h3, dates in .card__date (format: Del28/02/2026al19/03/2026)
        event_card_selector=".card--event",
        title_selector="h3",
        link_selector="a",
        image_selector="img",
        date_selector=".card__date",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.visitvalencia.com{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".field-name-body, .node-content, article .content, .field--name-body",
    ),
    # ---- CASTILLA-LA MANCHA ----
    BronzeSourceConfig(
        slug="clm_turismo",
        name="Turismo Castilla-La Mancha - Agenda",
        listing_url="https://www.turismocastillalamancha.es/es/agenda",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Toledo",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        base_url="https://www.turismocastillalamancha.es",
        # AEM CMS — 12 eventos en .card.card-js
        # data-title attr for title, data-img for image, a.card__img for link
        # Date in .dynamic-list-events__card-date--day/month/year
        event_card_selector=".card.card-js",
        title_selector="a.card__img",  # Title from data-title attr on card parent
        link_selector="a.card__img",
        image_selector="img",
        date_selector=".dynamic-list-events__card-date--day",
        location_selector=".location, .localidad",
        requires_detail_fetch=True,
        max_pages=1,
        detail_url_pattern="https://www.turismocastillalamancha.es{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".description, .descripcion, .content, article .text",
    ),
    # ---- LA RIOJA ----
    BronzeSourceConfig(
        slug="riojaforum",
        name="Riojaforum - Palacio de Congresos de La Rioja",
        listing_url="https://riojaforum.com/agenda",
        ccaa="La Rioja",
        ccaa_code="RI",
        province="La Rioja",
        city="Logroño",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        base_url="https://riojaforum.com",
        # GNOSS CMS — 12 eventos
        # Thumbnails in div.miniaturaListado > .miniatura > a > img
        # Titles in h2.group.title > a (inside .wrapDescription, NOT inside .listado)
        event_card_selector="div.group.miniaturaListado",
        title_selector=".miniatura a img",  # Title from img alt attr
        link_selector=".miniatura a",
        image_selector=".miniatura img",
        date_selector=".fecha, time",
        requires_detail_fetch=True,
        max_pages=2,
        page_param="pagina",
        detail_url_pattern="{id}",
        detail_id_extractor="url_suffix",
        detail_description_selector=".resource-description, .description, .content, article .text",
    ),
]

# Register all Bronze sources
SourceRegistry.register_many(BRONZE_SOURCES)


def get_bronze_source(slug: str) -> BronzeSourceConfig | None:
    """Get a Bronze source by slug.

    Args:
        slug: Source identifier

    Returns:
        BronzeSourceConfig or None
    """
    source = SourceRegistry.get(slug)
    if source and isinstance(source, BronzeSourceConfig):
        return source
    return None


def get_all_bronze_sources() -> list[BronzeSourceConfig]:
    """Get all Bronze sources.

    Returns:
        List of BronzeSourceConfig
    """
    return [
        s for s in SourceRegistry.get_by_tier(SourceTier.BRONZE)
        if isinstance(s, BronzeSourceConfig)
    ]


# ============================================================
# REGIONAL HELPERS
# ============================================================

# Castilla-La Mancha municipalities by province for locality detection
CLM_ALBACETE_MUNICIPALITIES = {
    "albacete", "hellín", "villarrobledo", "almansa", "la roda",
    "caudete", "tobarra", "chinchilla", "casas-ibáñez", "madrigueras",
}

CLM_CIUDAD_REAL_MUNICIPALITIES = {
    "ciudad real", "puertollano", "tomelloso", "alcázar de san juan",
    "alcazar de san juan", "valdepeñas", "manzanares", "daimiel",
    "la solana", "miguelturra", "argamasilla de alba", "campo de criptana",
    "socuéllamos", "bolaños", "almagro", "villanueva de los infantes",
    "herencia", "pedro muñoz",
}

CLM_CUENCA_MUNICIPALITIES = {
    "cuenca", "tarancón", "san clemente", "motilla del palancar",
    "quintanar del rey", "las pedroñeras", "iniesta", "villanueva de la jara",
}

CLM_GUADALAJARA_MUNICIPALITIES = {
    "guadalajara", "azuqueca de henares", "alovera", "el casar",
    "sigüenza", "molina de aragón", "marchamalo", "cabanillas del campo",
    "villanueva de la torre", "cifuentes", "brihuega",
}

CLM_TOLEDO_MUNICIPALITIES = {
    "toledo", "talavera de la reina", "illescas", "seseña", "torrijos",
    "madridejos", "fuensalida", "ocaña", "mora", "quintanar de la orden",
    "sonseca", "consuegra", "villacañas", "bargas", "añover de tajo",
}


def get_clm_province(locality: str) -> str:
    """Determine province from locality name in Castilla-La Mancha.

    Args:
        locality: Locality/city name

    Returns:
        Province name (defaults to Toledo)
    """
    if not locality:
        return "Toledo"

    lower = locality.lower().strip().replace("(capital)", "").strip()

    if any(m in lower or lower in m for m in CLM_ALBACETE_MUNICIPALITIES):
        return "Albacete"
    if any(m in lower or lower in m for m in CLM_CIUDAD_REAL_MUNICIPALITIES):
        return "Ciudad Real"
    if any(m in lower or lower in m for m in CLM_CUENCA_MUNICIPALITIES):
        return "Cuenca"
    if any(m in lower or lower in m for m in CLM_GUADALAJARA_MUNICIPALITIES):
        return "Guadalajara"
    if any(m in lower or lower in m for m in CLM_TOLEDO_MUNICIPALITIES):
        return "Toledo"

    # Check province name directly
    if "albacete" in lower:
        return "Albacete"
    if "ciudad real" in lower:
        return "Ciudad Real"
    if "cuenca" in lower:
        return "Cuenca"
    if "guadalajara" in lower:
        return "Guadalajara"
    if "toledo" in lower:
        return "Toledo"

    return "Toledo"
