"""Bronze-level web scraping source configurations.

Bronze sources require Firecrawl for JS rendering and BeautifulSoup for parsing.
These are the most complex sources requiring custom selectors per site.

Includes:
- Regional government agendas (CLM, Canarias, Navarra, Asturias, La Rioja)
- City agendas (Badajoz, Teruel)
- Viralagenda aggregator (Andalucía, CyL, Galicia, etc.)
"""

from dataclasses import field as dataclass_field

from src.config.sources import (
    BronzeSourceConfig,
    SourceRegistry,
    SourceTier,
)

# ============================================================
# BRONZE SOURCE CONFIGURATIONS
# ============================================================

BRONZE_SOURCES: list[BronzeSourceConfig] = [
    # ============================================================
    # CASTILLA-LA MANCHA
    # ============================================================
    BronzeSourceConfig(
        slug="clm_agenda",
        name="Agenda Cultural de Castilla-La Mancha",
        listing_url="https://agendacultural.castillalamancha.es",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Toledo",  # Default, detected from locality
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        event_card_selector=".view-actividades .views-row article.node--type-actividad",
        title_selector=".field--name-title p",
        link_selector="a.article__link",
        image_selector=".field--name-field-image img",
        date_selector=".field--name-field-fecha-actividad",
        requires_detail_fetch=True,
        max_pages=5,
    ),
    # ============================================================
    # CANARIAS (2 sources)
    # ============================================================
    BronzeSourceConfig(
        slug="canarias_lagenda",
        name="Lagenda - Agenda de eventos en Tenerife",
        listing_url="https://lagenda.org/programacion",
        ccaa="Canarias",
        ccaa_code="CN",
        province="Santa Cruz de Tenerife",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        event_card_selector=".small-post",
        title_selector="h4.title a",
        image_selector=".thumb img",
        date_selector=".post-date .date-display-single",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="canarias_grancanaria",
        name="Cultura Gran Canaria - Cabildo",
        listing_url="https://cultura.grancanaria.com/agenda/",
        ccaa="Canarias",
        ccaa_code="CN",
        province="Las Palmas",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        event_card_selector=".calendar-booking-item",
        title_selector="h3.title",
        link_selector="a[href*=detalle-agenda]",
        date_selector=".time-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ============================================================
    # ARAGÓN (Teruel)
    # ============================================================
    BronzeSourceConfig(
        slug="teruel_ayuntamiento",
        name="Agenda Cultural Ayuntamiento de Teruel",
        listing_url="https://www.teruel.es/eventos/feed/",
        ccaa="Aragón",
        ccaa_code="AR",
        province="Teruel",
        city="Teruel",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        event_card_selector="item",
        title_selector="title",
        link_selector="link",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ============================================================
    # NAVARRA
    # ============================================================
    BronzeSourceConfig(
        slug="navarra_cultura",
        name="Cultura Navarra - Gobierno de Navarra",
        listing_url="https://www.culturanavarra.es/es/agenda",
        ccaa="Navarra",
        ccaa_code="NA",
        province="Navarra",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        event_card_selector=".agenda_evento",
        title_selector="h4 a",
        link_selector="h4 a",
        image_selector="img.btn-block",
        date_selector=".fecha",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ============================================================
    # ASTURIAS
    # ============================================================
    BronzeSourceConfig(
        slug="asturias_turismo",
        name="Turismo Asturias - Agenda de Eventos",
        listing_url="https://www.turismoasturias.es/es/agenda-de-asturias",
        ccaa="Principado de Asturias",
        ccaa_code="AS",
        province="Asturias",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        event_card_selector=".card",
        title_selector=".card-title",
        link_selector="a",
        image_selector="img",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ============================================================
    # LA RIOJA
    # ============================================================
    BronzeSourceConfig(
        slug="larioja_agenda",
        name="Agenda de La Rioja - LARIOJA.COM",
        listing_url="https://agenda.larioja.com/",
        ccaa="La Rioja",
        ccaa_code="RI",
        province="La Rioja",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,  # Server-rendered
        event_card_selector="article",
        title_selector=".voc-agenda-titulo a, .voc-agenda-titulo2 a",
        link_selector=".voc-agenda-titulo a, .voc-agenda-titulo2 a",
        image_selector="img.figure-img",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ============================================================
    # EXTREMADURA (Badajoz)
    # ============================================================
    BronzeSourceConfig(
        slug="badajoz_agenda",
        name="Agenda Cultural Ayuntamiento de Badajoz",
        listing_url="https://www.aytobadajoz.es/es/ayto/agenda/",
        ccaa="Extremadura",
        ccaa_code="EX",
        province="Badajoz",
        city="Badajoz",
        tier=SourceTier.BRONZE,
        uses_firecrawl=True,
        event_card_selector=".agenda-listado.evento",
        title_selector=".titulo a",
        link_selector=".titulo a",
        image_selector=".imagen-evento img",
        date_selector=".fechas-agenda-menu-actualidad",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ============================================================
    # VIRALAGENDA SOURCES
    # These use the same structure, different URLs per province
    # ============================================================
    # ---- EXTREMADURA (Cáceres) ----
    BronzeSourceConfig(
        slug="viralagenda_caceres",
        name="Viral Agenda - Cáceres",
        listing_url="https://www.viralagenda.com/es/extremadura/caceres/caceres",
        ccaa="Extremadura",
        ccaa_code="EX",
        province="Cáceres",
        city="Cáceres",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- ANDALUCÍA (8 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_almeria",
        name="Viral Agenda - Almería",
        listing_url="https://www.viralagenda.com/es/andalucia/almeria",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Almería",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_cadiz",
        name="Viral Agenda - Cádiz",
        listing_url="https://www.viralagenda.com/es/andalucia/cadiz",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Cádiz",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_cordoba",
        name="Viral Agenda - Córdoba",
        listing_url="https://www.viralagenda.com/es/andalucia/cordoba",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Córdoba",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_granada",
        name="Viral Agenda - Granada",
        listing_url="https://www.viralagenda.com/es/andalucia/granada",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Granada",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_huelva",
        name="Viral Agenda - Huelva",
        listing_url="https://www.viralagenda.com/es/andalucia/huelva",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Huelva",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_jaen",
        name="Viral Agenda - Jaén",
        listing_url="https://www.viralagenda.com/es/andalucia/jaen",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Jaén",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_malaga",
        name="Viral Agenda - Málaga",
        listing_url="https://www.viralagenda.com/es/andalucia/malaga",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Málaga",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_sevilla",
        name="Viral Agenda - Sevilla",
        listing_url="https://www.viralagenda.com/es/andalucia/sevilla",
        ccaa="Andalucía",
        ccaa_code="AN",
        province="Sevilla",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- CASTILLA Y LEÓN (9 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_avila",
        name="Viral Agenda - Ávila",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/avila",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Ávila",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_burgos",
        name="Viral Agenda - Burgos",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/burgos",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Burgos",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_leon",
        name="Viral Agenda - León",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/leon",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="León",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_palencia",
        name="Viral Agenda - Palencia",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/palencia",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Palencia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_salamanca",
        name="Viral Agenda - Salamanca",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/salamanca",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Salamanca",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_segovia",
        name="Viral Agenda - Segovia",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/segovia",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Segovia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_soria",
        name="Viral Agenda - Soria",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/soria",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Soria",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_valladolid",
        name="Viral Agenda - Valladolid",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/valladolid",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Valladolid",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_zamora",
        name="Viral Agenda - Zamora",
        listing_url="https://www.viralagenda.com/es/castilla-y-leon/zamora",
        ccaa="Castilla y León",
        ccaa_code="CL",
        province="Zamora",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- GALICIA (4 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_a_coruna",
        name="Viral Agenda - A Coruña",
        listing_url="https://www.viralagenda.com/es/galicia/a-coruna",
        ccaa="Galicia",
        ccaa_code="GA",
        province="A Coruña",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_lugo",
        name="Viral Agenda - Lugo",
        listing_url="https://www.viralagenda.com/es/galicia/lugo",
        ccaa="Galicia",
        ccaa_code="GA",
        province="Lugo",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_ourense",
        name="Viral Agenda - Ourense",
        listing_url="https://www.viralagenda.com/es/galicia/ourense",
        ccaa="Galicia",
        ccaa_code="GA",
        province="Ourense",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_pontevedra",
        name="Viral Agenda - Pontevedra",
        listing_url="https://www.viralagenda.com/es/galicia/pontevedra",
        ccaa="Galicia",
        ccaa_code="GA",
        province="Pontevedra",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- ASTURIAS (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_asturias",
        name="Viral Agenda - Asturias",
        listing_url="https://www.viralagenda.com/es/asturias",
        ccaa="Asturias",
        ccaa_code="AS",
        province="Asturias",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- CANARIAS (Viralagenda - 2 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_las_palmas",
        name="Viral Agenda - Las Palmas",
        listing_url="https://www.viralagenda.com/es/canarias/las-palmas",
        ccaa="Canarias",
        ccaa_code="CN",
        province="Las Palmas",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_santa_cruz_tenerife",
        name="Viral Agenda - Santa Cruz de Tenerife",
        listing_url="https://www.viralagenda.com/es/canarias/santa-cruz-de-tenerife",
        ccaa="Canarias",
        ccaa_code="CN",
        province="Santa Cruz de Tenerife",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- CANTABRIA (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_cantabria",
        name="Viral Agenda - Cantabria",
        listing_url="https://www.viralagenda.com/es/cantabria",
        ccaa="Cantabria",
        ccaa_code="CB",
        province="Cantabria",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- LA RIOJA (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_la_rioja",
        name="Viral Agenda - La Rioja",
        listing_url="https://www.viralagenda.com/es/la-rioja",
        ccaa="La Rioja",
        ccaa_code="RI",
        province="La Rioja",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- MURCIA (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_murcia",
        name="Viral Agenda - Murcia",
        listing_url="https://www.viralagenda.com/es/murcia",
        ccaa="Región de Murcia",
        ccaa_code="MC",
        province="Murcia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- NAVARRA (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_navarra",
        name="Viral Agenda - Navarra",
        listing_url="https://www.viralagenda.com/es/navarra",
        ccaa="Navarra",
        ccaa_code="NC",
        province="Navarra",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- PAÍS VASCO (Viralagenda - 3 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_araba",
        name="Viral Agenda - Araba/Álava",
        listing_url="https://www.viralagenda.com/es/pais-vasco/araba-alava",
        ccaa="País Vasco",
        ccaa_code="PV",
        province="Araba/Álava",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_bizkaia",
        name="Viral Agenda - Bizkaia",
        listing_url="https://www.viralagenda.com/es/pais-vasco/bizkaia",
        ccaa="País Vasco",
        ccaa_code="PV",
        province="Bizkaia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_gipuzkoa",
        name="Viral Agenda - Gipuzkoa",
        listing_url="https://www.viralagenda.com/es/pais-vasco/gipuzkoa",
        ccaa="País Vasco",
        ccaa_code="PV",
        province="Gipuzkoa",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- ARAGÓN (Viralagenda - 3 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_huesca",
        name="Viral Agenda - Huesca",
        listing_url="https://www.viralagenda.com/es/aragon/huesca",
        ccaa="Aragón",
        ccaa_code="AR",
        province="Huesca",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_teruel",
        name="Viral Agenda - Teruel",
        listing_url="https://www.viralagenda.com/es/aragon/teruel",
        ccaa="Aragón",
        ccaa_code="AR",
        province="Teruel",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_zaragoza",
        name="Viral Agenda - Zaragoza",
        listing_url="https://www.viralagenda.com/es/aragon/zaragoza",
        ccaa="Aragón",
        ccaa_code="AR",
        province="Zaragoza",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- COMUNITAT VALENCIANA (Viralagenda - 3 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_alicante",
        name="Viral Agenda - Alicante",
        listing_url="https://www.viralagenda.com/es/comunitat-valenciana/alicante",
        ccaa="Comunitat Valenciana",
        ccaa_code="VC",
        province="Alicante",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_castellon",
        name="Viral Agenda - Castellón",
        listing_url="https://www.viralagenda.com/es/comunitat-valenciana/castellon",
        ccaa="Comunitat Valenciana",
        ccaa_code="VC",
        province="Castellón",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_valencia",
        name="Viral Agenda - Valencia",
        listing_url="https://www.viralagenda.com/es/comunitat-valenciana/valencia",
        ccaa="Comunitat Valenciana",
        ccaa_code="VC",
        province="Valencia",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- CATALUÑA (Viralagenda - 4 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_barcelona",
        name="Viral Agenda - Barcelona",
        listing_url="https://www.viralagenda.com/es/cataluna/barcelona",
        ccaa="Cataluña",
        ccaa_code="CT",
        province="Barcelona",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_girona",
        name="Viral Agenda - Girona",
        listing_url="https://www.viralagenda.com/es/cataluna/girona",
        ccaa="Cataluña",
        ccaa_code="CT",
        province="Girona",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_lleida",
        name="Viral Agenda - Lleida",
        listing_url="https://www.viralagenda.com/es/cataluna/lleida",
        ccaa="Cataluña",
        ccaa_code="CT",
        province="Lleida",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_tarragona",
        name="Viral Agenda - Tarragona",
        listing_url="https://www.viralagenda.com/es/cataluna/tarragona",
        ccaa="Cataluña",
        ccaa_code="CT",
        province="Tarragona",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- ILLES BALEARS (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_baleares",
        name="Viral Agenda - Illes Balears",
        listing_url="https://www.viralagenda.com/es/illes-balears",
        ccaa="Illes Balears",
        ccaa_code="IB",
        province="Illes Balears",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- COMUNIDAD DE MADRID (Viralagenda) ----
    BronzeSourceConfig(
        slug="viralagenda_madrid",
        name="Viral Agenda - Madrid",
        listing_url="https://www.viralagenda.com/es/madrid",
        ccaa="Comunidad de Madrid",
        ccaa_code="MD",
        province="Madrid",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- CASTILLA-LA MANCHA (Viralagenda - 5 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_albacete",
        name="Viral Agenda - Albacete",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/albacete",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Albacete",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_ciudad_real",
        name="Viral Agenda - Ciudad Real",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/ciudad-real",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Ciudad Real",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_cuenca",
        name="Viral Agenda - Cuenca",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/cuenca",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Cuenca",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_guadalajara",
        name="Viral Agenda - Guadalajara",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/guadalajara",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Guadalajara",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    BronzeSourceConfig(
        slug="viralagenda_toledo",
        name="Viral Agenda - Toledo",
        listing_url="https://www.viralagenda.com/es/castilla-la-mancha/toledo",
        ccaa="Castilla-La Mancha",
        ccaa_code="CM",
        province="Toledo",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
    # ---- EXTREMADURA (Viralagenda - 2 provinces) ----
    BronzeSourceConfig(
        slug="viralagenda_badajoz",
        name="Viral Agenda - Badajoz",
        listing_url="https://www.viralagenda.com/es/extremadura/badajoz",
        ccaa="Extremadura",
        ccaa_code="EX",
        province="Badajoz",
        city="",
        tier=SourceTier.BRONZE,
        uses_firecrawl=False,
        event_card_selector="li.viral-event",
        title_selector=".viral-event-title a",
        link_selector=".viral-event-title a",
        date_selector=".viral-event-date",
        requires_detail_fetch=True,
        max_pages=1,
    ),
]

# Register all Bronze sources
SourceRegistry.register_many(BRONZE_SOURCES)


def get_bronze_source(slug: str) -> BronzeSourceConfig | None:
    """Get a Bronze source by slug.

    Args:
        slug: Source identifier

    Returns:
        BronzeSourceConfig or None
    """
    source = SourceRegistry.get(slug)
    if source and isinstance(source, BronzeSourceConfig):
        return source
    return None


def get_all_bronze_sources() -> list[BronzeSourceConfig]:
    """Get all Bronze sources.

    Returns:
        List of BronzeSourceConfig
    """
    return [
        s for s in SourceRegistry.get_by_tier(SourceTier.BRONZE)
        if isinstance(s, BronzeSourceConfig)
    ]


# ============================================================
# REGIONAL HELPERS
# ============================================================

# Castilla-La Mancha municipalities by province for locality detection
CLM_ALBACETE_MUNICIPALITIES = {
    "albacete", "hellín", "villarrobledo", "almansa", "la roda",
    "caudete", "tobarra", "chinchilla", "casas-ibáñez", "madrigueras",
}

CLM_CIUDAD_REAL_MUNICIPALITIES = {
    "ciudad real", "puertollano", "tomelloso", "alcázar de san juan",
    "alcazar de san juan", "valdepeñas", "manzanares", "daimiel",
    "la solana", "miguelturra", "argamasilla de alba", "campo de criptana",
    "socuéllamos", "bolaños", "almagro", "villanueva de los infantes",
    "herencia", "pedro muñoz",
}

CLM_CUENCA_MUNICIPALITIES = {
    "cuenca", "tarancón", "san clemente", "motilla del palancar",
    "quintanar del rey", "las pedroñeras", "iniesta", "villanueva de la jara",
}

CLM_GUADALAJARA_MUNICIPALITIES = {
    "guadalajara", "azuqueca de henares", "alovera", "el casar",
    "sigüenza", "molina de aragón", "marchamalo", "cabanillas del campo",
    "villanueva de la torre", "cifuentes", "brihuega",
}

CLM_TOLEDO_MUNICIPALITIES = {
    "toledo", "talavera de la reina", "illescas", "seseña", "torrijos",
    "madridejos", "fuensalida", "ocaña", "mora", "quintanar de la orden",
    "sonseca", "consuegra", "villacañas", "bargas", "añover de tajo",
}


def get_clm_province(locality: str) -> str:
    """Determine province from locality name in Castilla-La Mancha.

    Args:
        locality: Locality/city name

    Returns:
        Province name (defaults to Toledo)
    """
    if not locality:
        return "Toledo"

    lower = locality.lower().strip().replace("(capital)", "").strip()

    if any(m in lower or lower in m for m in CLM_ALBACETE_MUNICIPALITIES):
        return "Albacete"
    if any(m in lower or lower in m for m in CLM_CIUDAD_REAL_MUNICIPALITIES):
        return "Ciudad Real"
    if any(m in lower or lower in m for m in CLM_CUENCA_MUNICIPALITIES):
        return "Cuenca"
    if any(m in lower or lower in m for m in CLM_GUADALAJARA_MUNICIPALITIES):
        return "Guadalajara"
    if any(m in lower or lower in m for m in CLM_TOLEDO_MUNICIPALITIES):
        return "Toledo"

    # Check province name directly
    if "albacete" in lower:
        return "Albacete"
    if "ciudad real" in lower:
        return "Ciudad Real"
    if "cuenca" in lower:
        return "Cuenca"
    if "guadalajara" in lower:
        return "Guadalajara"
    if "toledo" in lower:
        return "Toledo"

    return "Toledo"
